
spring:
  application:
    name: "retailsoft"
  datasource:
    url: jdbc:mysql://localhost:3306/bluedart
    username: root
    password: Dhoni@1996
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    
server:
  port: "8080"
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        